image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

unit_test:
  stage: test
  script:
  - coverage run -m unittest discover 
  - coverage report --omit="*/test*","*__init__.py"