image: "python:3.8"

before_script:
  - python --version
  - pip install pandas
  - pip install matplotlib

unit_test:
  stage: test
  script:
  - python test/test_results_test.py
  - python test/test_ensemble_test.py